# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-12-15 17:10:16
"""
import arcpy
from PC414CWIMillionAcres.AssignDomains import AssignDomains
from PC414CWIMillionAcres.AssignDomains import AssignDomains
from PC414CWIMillionAcres.AssignDomains import AssignDomains
from sys import argv

def Model41():  # 8 Append 20221215

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Model Environment settings
    with arcpy.EnvManager(outputCoordinateSystem="GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]"):
        CalTrans_act_ln_enriched_20220712c = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\CalTrans_act_ln_enriched_20220712c"
        CM_CNRAExtract_TrtLn_enriched_20221212 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\CM_CNRAExtract_TrtLn_enriched_20221212"
        e_Appended_3_ = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\e_Appended"
        WFR_TF_Template_2_ = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\b_Reference\\WFR_TF_Template"
        nfpors_fuels_treatments_pts_enriched_20221110 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\nfpors_fuels_treatments_pts_enriched_20221110"
        StateParks_XY_enriched_20220708 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\StateParks_XY_enriched_20220708"
        CalTrans_act_pts_enriched_20220712c = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\CalTrans_act_pts_enriched_20220712c"
        SCC_points_enriched_20221101 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\SCC_points_enriched_20221101"
        CM_CNRAExtract_TrtPnt_enriched_20221212 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\CM_CNRAExtract_TrtPnt_enriched_20221212"
        PFIRS_enriched_20221001 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\PFIRS_enriched_20221001"
        e_Appended_2_ = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\e_Appended"
        nfpors_fuels_treatments_enriched_20220906 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\nfpors_fuels_treatments_enriched_20220906"
        State_Parks_enriched_20220623 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\State_Parks_enriched_20220623"
        CalVTP_enriched_20220923 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\CalVTP_enriched_20220923"
        Tahoe_Forest_Fuels_Tx_enriched_20221017 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\Tahoe_Forest_Fuels_Tx_enriched_20221017"
        usfs_edw_facts_common_attributes_enriched_20220912 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\usfs_edw_facts_common_attributes_enriched_20220912"
        nps_flat_fuels_enriched_20221102 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\nps_flat_fuels_enriched_20221102"
        SCC_poly_enriched_20221101 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\SCC_poly_enriched_20221101"
        CM_CNRAExtract_TrtPoly_enriched_20221212 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\CM_CNRAExtract_TrtPoly_enriched_20221212"
        WCB_enriched_20221114 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\WCB_enriched_20221114"
        CNRA_Enriched_20221212 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\CNRA_Enriched_20221212"
        BLM_enriched_20220917 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\d_Enriched\\BLM_enriched_20220917"
        e_Appended = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\e_Appended"

        # Process: Create Line Feature Class (Create Feature Class) (management)
        Treat_n_harvests_lines_20221030 = arcpy.management.CreateFeatureclass(out_path=e_Appended_3_, out_name="Treat_n_harvests_lines_20221215", geometry_type="POLYLINE", template=[WFR_TF_Template_2_], has_m="DISABLED", has_z="DISABLED", spatial_reference="GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision", config_keyword="", spatial_grid_1=0, spatial_grid_2=0, spatial_grid_3=0, out_alias="")[0]

        # Process: Append Lines (Append) (management)
        Treat_n_harvests_line_20220917_2_ = arcpy.management.Append(inputs=[CalTrans_act_ln_enriched_20220712c, CM_CNRAExtract_TrtLn_enriched_20221212], target=Treat_n_harvests_lines_20221030, schema_type="TEST", field_mapping="", subtype="", expression="")[0]

        # Process: 2b Assign Domains (2b Assign Domains) (PC414CWIMillionAcres)
        WFR_TF_Template_3_ = AssignDomains(WFR_TF_Template=Treat_n_harvests_line_20220917_2_)[0]

        # Process: Create Point Feature Class (Create Feature Class) (management)
        Treat_n_harvests_points_20221030 = arcpy.management.CreateFeatureclass(out_path=e_Appended_2_, out_name="Treat_n_harvests_points_20221215", geometry_type="POINT", template=[WFR_TF_Template_2_], has_m="DISABLED", has_z="DISABLED", spatial_reference="GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision", config_keyword="", spatial_grid_1=0, spatial_grid_2=0, spatial_grid_3=0, out_alias="")[0]

        # Process: Append Points (Append) (management)
        Treat_n_harvests_point_20220917_2_ = arcpy.management.Append(inputs=[nfpors_fuels_treatments_pts_enriched_20221110, StateParks_XY_enriched_20220708, CalTrans_act_pts_enriched_20220712c, SCC_points_enriched_20221101, CM_CNRAExtract_TrtPnt_enriched_20221212, PFIRS_enriched_20221001], target=Treat_n_harvests_points_20221030, schema_type="TEST", field_mapping="", subtype="", expression="")[0]

        # Process: 2b Assign Domains (2) (2b Assign Domains) (PC414CWIMillionAcres)
        WFR_TF_Template_5_ = AssignDomains(WFR_TF_Template=Treat_n_harvests_point_20220917_2_)[0]

        # Process: Select (Select) (analysis)
        Treat_n_harvests_lines_20221212 = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\PC414 CWI Million Acres.gdb\\e_Appended\\Treat_n_harvests_lines_20221212"
        arcpy.analysis.Select(in_features=WCB_enriched_20221114, out_feature_class=Treat_n_harvests_lines_20221212, where_clause="Crosswalk NOT LIKE 'Restoration/Enhancement%'")

        # Process: Select (2) (Select) (analysis)
        CNRA_Treatments_20221_Select = "C:\\Users\\sageg\\Documents\\ArcGIS\\Projects\\PC414 CWI Million Acres\\scratch.gdb\\CNRA_Treatments_20221_Select"
        arcpy.analysis.Select(in_features=CNRA_Enriched_20221212, out_feature_class=CNRA_Treatments_20221_Select, where_clause="ADMINISTERING_ORG <> 'CDF'")

        # Process: Create Polygon Feature Class (Create Feature Class) (management)
        Treat_n_harvests_polygons_20221030 = arcpy.management.CreateFeatureclass(out_path=e_Appended, out_name="Treat_n_harvests_polygons_20221215", geometry_type="POLYGON", template=[WFR_TF_Template_2_], has_m="DISABLED", has_z="DISABLED", spatial_reference="PROJCS[\"NAD_1983_California_Teale_Albers\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Albers\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",-4000000.0],PARAMETER[\"Central_Meridian\",-120.0],PARAMETER[\"Standard_Parallel_1\",34.0],PARAMETER[\"Standard_Parallel_2\",40.5],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]];-16909700 -8597000 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision", config_keyword="", spatial_grid_1=0, spatial_grid_2=0, spatial_grid_3=0, out_alias="")[0]

        # Process: Append Polygoins (Append) (management)
        Updated_Target_Dataset = arcpy.management.Append(inputs=[nfpors_fuels_treatments_enriched_20220906, State_Parks_enriched_20220623, CalVTP_enriched_20220923, Tahoe_Forest_Fuels_Tx_enriched_20221017, usfs_edw_facts_common_attributes_enriched_20220912, nps_flat_fuels_enriched_20221102, SCC_poly_enriched_20221101, CM_CNRAExtract_TrtPoly_enriched_20221212, Treat_n_harvests_lines_20221212, CNRA_Treatments_20221_Select, BLM_enriched_20220917], target=Treat_n_harvests_polygons_20221030, schema_type="TEST", field_mapping="", subtype="", expression="")[0]

        # Process: 2b Assign Domains (3) (2b Assign Domains) (PC414CWIMillionAcres)
        WFR_TF_Template_4_ = AssignDomains(WFR_TF_Template=Updated_Target_Dataset)[0]

        return Treat_n_harvests_lines_20221030, Treat_n_harvests_polygons_20221030, Treat_n_harvests_points_20221030

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(extent="-124.415162172178 32.5342699477235 -114.131212866967 42.0095193288898 GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]", preserveGlobalIds=True, qualifiedFieldNames=False, 
                          scratchWorkspace=r"C:\Users\sageg\Documents\ArcGIS\Projects\PC414 CWI Million Acres\scratch.gdb", transferDomains=True, transferGDBAttributeProperties=True, 
                          workspace=r"C:\Users\sageg\Documents\ArcGIS\Projects\PC414 CWI Million Acres\PC414 CWI Million Acres.gdb"):
        Model41(*argv[1:])
