# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-12-15 17:10:16
"""
import arcpy
from sys import argv
from _2b_assign_domains import AssignDomains
from utils import init_gdb, delete_scratch_files
import os
import datetime
original_gdb, workspace, scratch_workspace = init_gdb()
date_id = datetime.datetime.utcnow().strftime("%Y-%m-%d").replace('-','') # like 20221216

def Model41():  # 8 Append 20230120

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    # Model Environment settings
    with arcpy.EnvManager(outputCoordinateSystem="""GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]"""):
        
        # INPUTS
        # Reference
        WFR_TF_Template = os.path.join(workspace,'b_Reference','WFR_TF_Template')
        
        # Point
        nfpors_fuels_treatments_pts_enriched = os.path.join(workspace,'d_Enriched','nfpors_fuels_treatments_pts_enriched_20221110')
        StateParks_XY_enriched = os.path.join(workspace,'d_Enriched','StateParks_XY_enriched_20220708')
        CalTrans_act_pts_enriched = os.path.join(workspace,'d_Enriched','CalTrans_act_pts_enriched_20220712c')
        SCC_points_enriched = os.path.join(workspace,'d_Enriched','SCC_points_enriched_20221101')
        CM_CNRAExtract_TrtPnt_enriched = os.path.join(workspace,'d_Enriched','CM_CNRAExtract_TrtPnt_enriched_20221212')
        PFIRS_enriched = os.path.join(workspace,'d_Enriched','PFIRS_enriched_20221001')

        # Line
        CalTrans_act_ln_enriched = os.path.join(workspace,'d_Enriched','CalTrans_act_ln_enriched_20220712c')
        CM_CNRAExtract_TrtLn_enriched = os.path.join(workspace,'d_Enriched','CM_CNRAExtract_TrtLn_enriched_20221212')

        # Polygon
        nfpors_fuels_treatments_enriched = os.path.join(workspace,'d_Enriched','nfpors_fuels_treatments_enriched_20220906')
        State_Parks_enriched = os.path.join(workspace,'d_Enriched','State_Parks_enriched_20220623')
        CalVTP_enriched = os.path.join(workspace,'d_Enriched','CalVTP_enriched_20220923')
        Tahoe_Forest_Fuels_Tx_enriched = os.path.join(workspace,'d_Enriched','Tahoe_Forest_Fuels_Tx_enriched_20221017')
        usfs_edw_facts_common_attributes_enriched = os.path.join(workspace,'d_Enriched','usfs_edw_facts_common_attributes_enriched_20220912')
        nps_flat_fuels_enriched = os.path.join(workspace,'d_Enriched','nps_flat_fuels_enriched_20221102')
        SCC_poly_enriched = os.path.join(workspace,'d_Enriched','SCC_poly_enriched_20221101')
        CM_CNRAExtract_TrtPoly_enriched = os.path.join(workspace,'d_Enriched','CM_CNRAExtract_TrtPoly_enriched_20221212')
        WCB_enriched = os.path.join(workspace,'d_Enriched','WCB_enriched_20221114')
        CNRA_Enriched = os.path.join(workspace,'d_Enriched','CNRA_Enriched_20221212')
        BLM_enriched = os.path.join(workspace,'d_Enriched','BLM_enriched_20220917')

        # Process: Create Line Feature Class (Create Feature Class) (management)
        Treat_n_harvests_lines = arcpy.management.CreateFeatureclass(
            out_path=os.path.join(workspace,'e_Appended'), 
            out_name=f"Treat_n_harvests_lines_{date_id}", 
            geometry_type="POLYLINE", 
            template=[WFR_TF_Template], 
            has_m="DISABLED", 
            has_z="DISABLED", 
            spatial_reference="GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision", 
            config_keyword="", 
            spatial_grid_1=0, 
            spatial_grid_2=0, 
            spatial_grid_3=0, 
            out_alias=""
            )[0]

        # Process: Append Lines (Append) (management)
        Treat_n_harvests_line_append = arcpy.management.Append(
            inputs=[CalTrans_act_ln_enriched, 
                    CM_CNRAExtract_TrtLn_enriched
                    ], 
            target=Treat_n_harvests_lines, 
            schema_type="TEST", 
            field_mapping="", 
            subtype="", 
            expression=""
            )[0]

        # Process: 2b Assign Domains (2b Assign Domains) (PC414CWIMillionAcres)
        WFR_TF_Template_3_ = AssignDomains(in_table=Treat_n_harvests_line_append)[0]

        # Process: Create Point Feature Class (Create Feature Class) (management)
        Treat_n_harvests_points = arcpy.management.CreateFeatureclass(
            out_path=os.path.join(workspace,'e_Appended'), 
            out_name=f"Treat_n_harvests_points_{date_id}", 
            geometry_type="POINT", 
            template=[WFR_TF_Template], 
            has_m="DISABLED", 
            has_z="DISABLED", 
            spatial_reference="GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision", 
            config_keyword="", 
            spatial_grid_1=0, 
            spatial_grid_2=0, 
            spatial_grid_3=0, 
            out_alias=""
            )[0]

        # Process: Append Points (Append) (management)
        Treat_n_harvests_point_append = arcpy.management.Append(
            inputs=[nfpors_fuels_treatments_pts_enriched, 
                    StateParks_XY_enriched, 
                    CalTrans_act_pts_enriched, 
                    SCC_points_enriched, 
                    CM_CNRAExtract_TrtPnt_enriched, 
                    PFIRS_enriched
                    ], 
            target=Treat_n_harvests_points, 
            schema_type="TEST", 
            field_mapping="", 
            subtype="", expression=""
            )[0]

        # Process: 2b Assign Domains (2) (2b Assign Domains) (PC414CWIMillionAcres)
        WFR_TF_Template_5_ = AssignDomains(in_table=Treat_n_harvests_point_append)[0]

        # Process: Select (Select) (analysis)
        WCB_poly = os.path.join(scratch_workspace,'WCB_poly')
        arcpy.analysis.Select(
            in_features=WCB_enriched, 
            out_feature_class=WCB_poly, 
            where_clause="Crosswalk NOT LIKE 'Restoration/Enhancement%'"
            )

        # Process: Select (2) (Select) (analysis)
        CNRA_Treatments_20221_Select = os.path.join(scratch_workspace,'CNRA_Treatments_20221_Select')
        arcpy.analysis.Select(
            in_features=CNRA_Enriched, 
            out_feature_class=CNRA_Treatments_20221_Select, 
            where_clause="ADMINISTERING_ORG <> 'CALFIRE'"
            )

        # Process: Create Polygon Feature Class (Create Feature Class) (management)
        Treat_n_harvests_polygons = arcpy.management.CreateFeatureclass(
            out_path=os.path.join(workspace,'e_Appended'), 
            out_name=f"Treat_n_harvests_polygons_{date_id}", 
            geometry_type="POLYGON", 
            template=[WFR_TF_Template], 
            has_m="DISABLED", 
            has_z="DISABLED", 
            spatial_reference="PROJCS[\"NAD_1983_California_Teale_Albers\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Albers\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",-4000000.0],PARAMETER[\"Central_Meridian\",-120.0],PARAMETER[\"Standard_Parallel_1\",34.0],PARAMETER[\"Standard_Parallel_2\",40.5],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]];-16909700 -8597000 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision", 
            config_keyword="", 
            spatial_grid_1=0, 
            spatial_grid_2=0, 
            spatial_grid_3=0, 
            out_alias=""
            )[0]

        # Process: Append Polygoins (Append) (management)
        Treat_n_harvests_polygons_append = arcpy.management.Append(
            inputs=[nfpors_fuels_treatments_enriched, 
                    State_Parks_enriched, 
                    CalVTP_enriched, 
                    Tahoe_Forest_Fuels_Tx_enriched, 
                    usfs_edw_facts_common_attributes_enriched, 
                    nps_flat_fuels_enriched, 
                    SCC_poly_enriched, 
                    CM_CNRAExtract_TrtPoly_enriched, 
                    WCB_poly, 
                    CNRA_Treatments_20221_Select, 
                    BLM_enriched]
                    , 
            target=Treat_n_harvests_polygons, 
            schema_type="TEST", 
            field_mapping="", 
            subtype="", 
            expression=""
            )[0]

        # Process: 2b Assign Domains (3) (2b Assign Domains) (PC414CWIMillionAcres)
        WFR_TF_Template_4_ = AssignDomains(in_table=Treat_n_harvests_polygons_append)[0]

        return Treat_n_harvests_lines, Treat_n_harvests_polygons, Treat_n_harvests_points

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(extent="""-124.415162172178 32.5342699477235 -114.131212866967 42.0095193288898 GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]""", preserveGlobalIds=True, qualifiedFieldNames=False, 
                          scratchWorkspace=scratch_workspace, transferDomains=True, transferGDBAttributeProperties=True, 
                          workspace=workspace):
        Model41(*argv[1:])
